version: '3.11'
services:
  backend:
    container_name: django-backend
    build: .
    volumes: 
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=master
      - POSTGRES_USER=master
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: